'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {id,outputName,startRequest}=require('../src/common.cjs');
const {Dependencies}=require('../src/dependencies.cjs');
const {Engine}=require('../src/engine.cjs');
const {wave}=require('./fixtures.cjs');
const selected='อัลบั้มทดสอบ - Love Songs 80s';
test('custom Download Audio names validated and extensions generated by engine only',()=>{
 const r={sourceId:id(),folderId:id(),requestId:id(),encoding:{format:'original'},outputName:selected};
 startRequest(r,'download');
 assert.equal(outputName(r.outputName),selected);
 assert.equal(outputName('   ชื่อไทย   '),'ชื่อไทย');
 assert.equal(outputName(''),null);
 assert.equal(outputName(undefined),null);
 for(const bad of ['../escape','C:\\temp','album.flac','album.mp3','album.m4a','song.wav','CON','LPT1','COM9.txt','abc.','invalid|name','bad\u0001name','A'.repeat(111)]){
  assert.throws(()=>startRequest({...r,outputName:bad},'download'),{code:'INVALID_REQUEST'},bad);
 }
 assert.throws(()=>startRequest({...r,outputName:123},'download'),{code:'INVALID_REQUEST'});
 assert.throws(()=>startRequest({...r,outputName:selected,evil:'extra'},'download'),{code:'INVALID_REQUEST'});
 startRequest({...r,encoding:{format:'flac',bitsPerSample:24,sampleRateHz:'source'}},'convert');
 assert.throws(()=>startRequest({...r,outputName:'../escape',encoding:{format:'flac',bitsPerSample:24,sampleRateHz:'source'}},'convert'),{code:'INVALID_REQUEST'});
 assert.throws(()=>startRequest({...r,outputName:'album.flac',encoding:{format:'flac',bitsPerSample:24,sampleRateHz:'source'}},'convert'),{code:'INVALID_REQUEST'});
 assert.throws(()=>startRequest({...r,outputName:123,encoding:{format:'flac',bitsPerSample:24,sampleRateHz:'source'}},'convert'),{code:'INVALID_REQUEST'});
 startRequest({...r,outputName:'',encoding:{format:'original'}},'download');
 startRequest({sourceId:r.sourceId,folderId:r.folderId,requestId:r.requestId,encoding:{format:'original'}},'download');
});
test('real local publish uses optional name, collision suffix, blank legacy default, never overwrites',async()=>{
 const base=path.resolve('test-output/filename-job-'+Date.now());
 await fs.mkdir(base,{recursive:true});
 const input=path.join(base,'fixture.wav');
 await wave(input,2);
 const deps=await new Dependencies(path.resolve('vendor')).load();
 const engine=await new Engine({deps,dataDir:path.join(base,'state')}).init();
 const folder=await engine.registerFolder(base);
 const realRun=engine.runner.run.bind(engine.runner);
 const videoUrl='https://www.youtube.com/watch?v=abcdefghijk';
 const mediaInfo={id:'abcdefghijk',formats:[{acodec:'pcm_s16le',vcodec:'none'}],duration:2,ext:'wav',acodec:'pcm_s16le'};
 engine.runner.run=async(tool,args,opts)=>{
  if(tool==='ytDlp'&&args.includes('--dump-single-json'))return {stdout:JSON.stringify(mediaInfo),stderr:''};
  if(tool==='ytDlp'){
   const target=path.join(opts.cwd,'source.wav');
   await fs.copyFile(input,target);
   opts.onLine('ATL_RESULT '+JSON.stringify(target));
   return {stdout:'',stderr:''};
  }
  return realRun(tool,args,opts);
 };
 const sourceId=id();
 engine.sources.set(sourceId,{dto:{sourceId,mode:'download',displayName:'Fixture Album.wav',metadata:{durationSeconds:2,bytes:100000},validUntil:new Date(Date.now()+600000).toISOString()},url:videoUrl});
 async function job(name,includeName=true){
  const req={sourceId,folderId:folder.folderId,requestId:id(),encoding:{format:'original'}};
  if(includeName)req.outputName=name;
  await engine.start('download',req);await engine.work;
  assert.equal(engine.job.status,'succeeded',JSON.stringify(engine.job.error));
  const out=engine.snapshot().output;
  assert.equal((await fs.stat(out.displayPath)).size,(await fs.stat(input)).size);
  return out.fileName;
 }
 assert.equal(await job(selected),selected+'.wav');
 assert.equal(await job(selected),selected+' (1).wav');
 assert.equal(await job('',true),'Fixture Album — download.wav');
 assert.equal(await job('',false),'Fixture Album — download (1).wav');
 const original=await fs.readFile(input);
 assert.deepEqual(await fs.readFile(path.join(base,selected+'.wav')),original);
 assert.deepEqual(await fs.readFile(path.join(base,selected+' (1).wav')),original);
 console.log('Filename publishing checks PASS at '+base);
});
