const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {Engine}=require('../src/engine.cjs'),{Dependencies}=require('../src/dependencies.cjs'),{MediaError,id}=require('../src/common.cjs'),{wave}=require('./fixtures.cjs'),files=require('../src/files.cjs');
(async()=>{
 const root=path.resolve('test-output/lifecycle-'+Date.now());await fs.mkdir(root,{recursive:true});const deps=await new Dependencies(path.resolve('vendor')).load(),input=path.join(root,'native.wav');await wave(input);const results=[];
 // Inject failure in inspection only; proves lock release without pretending a provider was reached.
 const e=await new Engine({deps,dataDir:path.join(root,'state')}).init(),original=e.runner.run.bind(e.runner);e.runner.run=async(tool,...args)=>{if(tool==='ytDlp')throw new MediaError('NETWORK_FAILED','injected network failure');return original(tool,...args);};
 await assert.rejects(e.inspect({requestId:id(),url:'https://youtu.be/abcdefghijk'}));const s=await e.registerFile(input),f=await e.registerFolder(root);await e.start('convert',{sourceId:s.sourceId,folderId:f.folderId,requestId:id(),encoding:{format:'mp3',bitrateKbps:128}});await e.work;assert.equal(e.job.status,'succeeded');results.push('failed-inspection-does-not-lock-convert (fault injection)');
 // Move only our disposable output; native openResult must refuse its old path.
 const output=e.job.output;await fs.rename(output.displayPath,output.displayPath+'.moved');await assert.rejects(e.result({resultId:output.resultId,target:'file'}),x=>x.code==='FILE_MISSING');assert.equal(e.job.output.available,false);results.push('moved-output-disabled');
 const junction=path.join(root,'junction');await fs.symlink(root,junction,'junction');await assert.rejects(e.registerFolder(junction),x=>x.code==='ACCESS_DENIED');results.push('real-junction-rejected');
 const vanished=path.join(root,'vanished');await fs.mkdir(vanished);const vf=await e.registerFolder(vanished);await fs.rename(vanished,vanished+'-moved');await e.start('convert',{sourceId:s.sourceId,folderId:vf.folderId,requestId:id(),encoding:{format:'mp3',bitrateKbps:128}});await e.work;assert.notEqual(e.job.status,'succeeded');results.push('moved-destination-refused');
 // Kill an actual parent process; its helper loses the control pipe and destroys the Job Object.
 const host=path.join(root,'parent.cjs'),audit=path.join(root,'parent-audit.jsonl');
 await fs.writeFile(host,`const fs=require('node:fs');const {Dependencies}=require(${JSON.stringify(path.resolve('src/dependencies.cjs'))});const {Runner}=require(${JSON.stringify(path.resolve('src/runner.cjs'))});(async()=>{const d=await new Dependencies(${JSON.stringify(path.resolve('vendor'))}).load();await new Runner(d,e=>fs.appendFileSync(${JSON.stringify(audit)},JSON.stringify(e)+'\\n')).run('jsRuntime',['-e',"const p=require('node:child_process').spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'ignore'});console.log(p.pid);setInterval(()=>{},1000)"],{onLine:l=>fs.appendFileSync(${JSON.stringify(audit)},JSON.stringify({child:Number(l)})+'\\n')});})()`);
 const parent=spawn(path.resolve('vendor/node.exe'),[host],{windowsHide:true,stdio:'ignore'});let records=[];for(let i=0;i<100;i++){try{records=(await fs.readFile(audit,'utf8')).trim().split('\n').map(JSON.parse);}catch{}if(records.some(r=>r.child))break;await new Promise(r=>setTimeout(r,100));}
 assert(records.some(r=>r.child));parent.kill();await new Promise(r=>parent.once('close',r));await new Promise(r=>setTimeout(r,1500));const ids=records.flatMap(r=>r.pid?[r.pid]:r.child?[r.child]:[]);for(const pid of ids)assert.throws(()=>process.kill(pid,0));results.push({parentCrashKillsEntireTree:true,pids:ids});
 // Existing helper refusal cannot unlock the engine; staging remains for explicit recovery.
 const blocked=await new Engine({deps,dataDir:path.join(root,'blocked')}).init();const bs=await blocked.registerFile(input),bf=await blocked.registerFolder(root);const normal=blocked.runner.run.bind(blocked.runner);blocked.runner.run=async(tool,...args)=>{if(tool==='ffmpeg')throw new MediaError('CLEANUP_REQUIRED','injected helper acknowledgment loss');return normal(tool,...args);};let cleanupCalled=false;blocked.io.cleanup=async()=>{cleanupCalled=true;};await blocked.start('convert',{sourceId:bs.sourceId,folderId:bf.folderId,requestId:id(),encoding:{format:'mp3',bitrateKbps:192}});await blocked.work;assert.equal(blocked.job.status,'cleanup-required');assert.equal(cleanupCalled,false);assert(await fs.stat(blocked.staging));const reopened=await new Engine({deps,dataDir:path.join(root,'blocked')}).init();assert.equal(reopened.job.status,'cleanup-required');results.push('helper-failure-keeps-lock-and-does-not-delete-staging (fault injection)');
 await fs.writeFile(path.join(root,'results.json'),JSON.stringify({passed:true,results},null,2));console.log('LIFECYCLE PASS',root);
})().catch(e=>{console.error(e);process.exitCode=1;});
