// Test-only process-aware socket sampling. Does not capture payloads or unrelated process records.
using System;using System.IO;using System.Text;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Threading;using System.Net;
class NetworkWatch{
 [DllImport("iphlpapi.dll",SetLastError=true)]static extern uint GetExtendedTcpTable(IntPtr p,ref int n,bool sort,int family,int cls,int reserved);
 [DllImport("iphlpapi.dll",SetLastError=true)]static extern uint GetExtendedUdpTable(IntPtr p,ref int n,bool sort,int family,int cls,int reserved);
 static HashSet<int> pids=new HashSet<int>();static HashSet<string> seen=new HashSet<string>();static int samples=0,errors=0;
 static void Table(bool tcp,int family){int n=0;uint r=tcp?GetExtendedTcpTable(IntPtr.Zero,ref n,false,family,5,0):GetExtendedUdpTable(IntPtr.Zero,ref n,false,family,1,0);IntPtr p=Marshal.AllocHGlobal(n);try{r=tcp?GetExtendedTcpTable(p,ref n,false,family,5,0):GetExtendedUdpTable(p,ref n,false,family,1,0);if(r!=0){errors++;return;}int count=Marshal.ReadInt32(p);int stride=tcp?(family==2?24:56):(family==2?12:28),pidOffset=tcp?(family==2?20:52):(family==2?8:24);for(int i=0;i<count;i++){IntPtr row=IntPtr.Add(p,4+i*stride);int pid=Marshal.ReadInt32(row,pidOffset);if(!pids.Contains(pid))continue;string remote="none";if(tcp){byte[] bytes=new byte[family==2?4:16];Marshal.Copy(IntPtr.Add(row,family==2?12:24),bytes,0,bytes.Length);remote=new IPAddress(bytes).ToString();}seen.Add("{\"pid\":"+pid+",\"protocol\":\""+(tcp?"TCP":"UDP")+(family==2?"4":"6")+"\",\"remote\":\""+remote+"\"}");}}finally{Marshal.FreeHGlobal(p);}}
 static void Main(string[] args){Console.WriteLine("READY");DateTime end=DateTime.UtcNow.AddSeconds(int.Parse(args[2]));while(DateTime.UtcNow<end){try{foreach(string line in File.ReadAllLines(args[0])){int p;if(int.TryParse(line,out p))pids.Add(p);}}catch{}foreach(int family in new int[]{2,23}){Table(true,family);Table(false,family);}samples++;Thread.Sleep(50);}File.WriteAllText(args[1],"{\"samples\":"+samples+",\"intervalMs\":50,\"tableErrors\":"+errors+",\"pids\":["+string.Join(",",pids)+"],\"connections\":["+string.Join(",",seen)+"],\"method\":\"GetExtendedTcpTable/GetExtendedUdpTable IPv4/IPv6; sampling, not full ETW capture\"}");}
}
