const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),{execFile}=require("child_process");
const SPLITTER_ROOT=String.raw`D:\Projects\Audio Album Splitter AI`,PYTHON=path.join(SPLITTER_ROOT,".venv","Scripts","python.exe"),ANALYZE_SCRIPT=path.join(__dirname,"analyze-upload.py");
const PORT=8787,MAX=2000*1000*1000,CHUNK=8*1024*1024,ROOT=path.resolve(__dirname,"..","uploads"),EXPORT_ROOT=path.resolve(__dirname,"..","exports"),EXPORT_SCRIPT=path.join(__dirname,"export-upload.py");
fs.mkdirSync(EXPORT_ROOT,{recursive:true});
const RETENTION_MS=24*60*60*1000,CLEANUP_INTERVAL_MS=60*60*1000;
const sessions=new Map(); fs.mkdirSync(ROOT,{recursive:true});
function cleanupExpiredUploads(now=Date.now()){let deleted=0;for(const entry of fs.readdirSync(ROOT,{withFileTypes:true})){if(!entry.isFile())continue;const file=path.join(ROOT,entry.name);try{const stat=fs.statSync(file);if(now-stat.mtimeMs>=RETENTION_MS){fs.unlinkSync(file);deleted++}}catch(e){console.error("Cleanup skipped",entry.name,e.message)}}return deleted}
const initialCleanup=cleanupExpiredUploads();if(initialCleanup)console.log("Cleanup removed",initialCleanup,"expired upload(s)");
const cleanupTimer=setInterval(()=>{const n=cleanupExpiredUploads();if(n)console.log("Cleanup removed",n,"expired upload(s)")},CLEANUP_INTERVAL_MS);cleanupTimer.unref();
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type,X-Upload-Id,X-Chunk-Index","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
function send(res,code,obj){res.writeHead(code,{...cors,"Content-Type":"application/json; charset=utf-8"});res.end(JSON.stringify(obj))}
function body(req,limit=1024*1024){return new Promise((ok,bad)=>{let b=[],n=0;req.on("data",c=>{n+=c.length;if(n>limit){bad(new Error("body too large"));req.destroy();return}b.push(c)});req.on("end",()=>ok(Buffer.concat(b)));req.on("error",bad)})}
function safeName(n){return path.basename(n).replace(/[^a-zA-Z0-9._ -]/g,"_")}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==="OPTIONS"){res.writeHead(204,cors);return res.end()}
 if(req.method==="GET"&&req.url==="/health")return send(res,200,{ok:true,maxMB:2000,chunkMB:8});
 if(req.method==="POST"&&req.url==="/upload/init"){const d=JSON.parse((await body(req)).toString()||"{}"),name=safeName(d.name||""),ext=path.extname(name).toLowerCase();if(![".wav",".flac",".m4a"].includes(ext))return send(res,415,{error:"unsupported file type"});if(!Number.isSafeInteger(d.size)||d.size<=0||d.size>MAX)return send(res,413,{error:"file exceeds 2000 MB limit"});const id=crypto.randomUUID(),file=path.join(ROOT,id+".part");fs.writeFileSync(file,"");sessions.set(id,{id,name,size:d.size,file,received:0,next:0});return send(res,200,{uploadId:id,chunkSize:CHUNK})}
 if(req.method==="POST"&&req.url==="/upload/chunk"){const id=req.headers["x-upload-id"],s=sessions.get(id),idx=Number(req.headers["x-chunk-index"]);if(!s)return send(res,404,{error:"upload session not found"});if(idx!==s.next)return send(res,409,{error:"unexpected chunk",expected:s.next});const b=await body(req,CHUNK+1024);if(s.received+b.length>s.size||s.received+b.length>MAX)return send(res,413,{error:"upload exceeds declared size"});fs.appendFileSync(s.file,b);s.received+=b.length;s.next++;return send(res,200,{received:s.received,size:s.size})}
 if(req.method==="POST"&&req.url==="/upload/complete"){const d=JSON.parse((await body(req)).toString()||"{}"),s=sessions.get(d.uploadId);if(!s)return send(res,404,{error:"upload session not found"});if(s.received!==s.size)return send(res,409,{error:"upload incomplete",received:s.received,size:s.size});const final=path.join(ROOT,s.id+"-"+s.name);fs.renameSync(s.file,final);sessions.delete(s.id);return send(res,200,{ok:true,fileId:s.id,name:s.name,size:s.size})}
 if(req.method==="POST"&&req.url==="/analyze"){const d=JSON.parse((await body(req)).toString()||"{}"),id=String(d.fileId||"");if(!/^[0-9a-f-]{36}$/.test(id))return send(res,400,{error:"invalid fileId"});const matches=fs.readdirSync(ROOT).filter(n=>n.startsWith(id+"-"));if(matches.length!==1)return send(res,404,{error:"uploaded file not found"});const file=path.join(ROOT,matches[0]);return execFile(PYTHON,[ANALYZE_SCRIPT,file],{cwd:SPLITTER_ROOT,maxBuffer:4*1024*1024},(err,stdout,stderr)=>{if(err)return send(res,500,{error:(stderr||err.message).trim()});try{return send(res,200,JSON.parse(stdout))}catch(e){return send(res,500,{error:"invalid analyzer response"})}})}
 if(req.method==="POST"&&req.url==="/export"){const raw=await body(req),d=JSON.parse(raw.toString()||"{}"),id=String(d.fileId||""),format=String(d.format||"").toLowerCase();if(!/^[0-9a-f-]{36}$/.test(id)||!["wav","flac"].includes(format)||!Array.isArray(d.boundaries))return send(res,400,{error:"invalid export request"});const matches=fs.readdirSync(ROOT).filter(n=>n.startsWith(id+"-"));if(matches.length!==1)return send(res,404,{error:"uploaded file not found"});const child=execFile(PYTHON,[EXPORT_SCRIPT,path.join(ROOT,matches[0]),EXPORT_ROOT],{cwd:SPLITTER_ROOT,maxBuffer:4*1024*1024},(err,stdout,stderr)=>{if(err)return send(res,500,{error:(stderr||err.message).trim()});try{const out=JSON.parse(stdout);out.files=out.files.map(f=>({...f,url:"/download/"+out.jobId+"/"+encodeURIComponent(f.name)}));return send(res,200,out)}catch(e){return send(res,500,{error:"invalid export response"})}});return child.stdin.end(JSON.stringify({format,boundaries:d.boundaries}))}
 if(req.method==="GET"&&req.url.startsWith("/download/")){const parts=req.url.split("/").slice(2).map(decodeURIComponent);if(parts.length!==2||!/^[0-9a-f-]{36}$/.test(parts[0]))return send(res,400,{error:"invalid download"});const file=path.resolve(EXPORT_ROOT,parts[0],path.basename(parts[1]));if(!file.startsWith(path.resolve(EXPORT_ROOT)+path.sep)||!fs.existsSync(file))return send(res,404,{error:"file not found"});res.writeHead(200,{...cors,"Content-Type":"application/octet-stream","Content-Disposition":`attachment; filename="${path.basename(file).replace(/"/g,"")}"`,"Content-Length":fs.statSync(file).size});return fs.createReadStream(file).pipe(res)}
 send(res,404,{error:"not found"});
}catch(e){send(res,500,{error:e.message})}});
server.listen(PORT,"0.0.0.0",()=>console.log("Audio Tech Lab upload backend http://0.0.0.0:"+PORT));
