'use strict';
const fs = require('node:fs'), path = require('node:path');
const { demoOrigin, verifyDemo } = require('./deployment-config.cjs');
async function buildPages({ root = path.resolve(__dirname, '..'), origin = process.env.ATL_DEMO_ORIGIN, verify = verifyDemo } = {}) {
  const endpoint = demoOrigin(origin);
  if (endpoint) await verify(endpoint);
  const buildRoot = path.resolve(root, '.site-build'), output = path.join(buildRoot, 'pages');
  const marker = path.join(buildRoot, '.generated-by-atl');
  if (fs.existsSync(buildRoot) && !fs.existsSync(marker)) throw new Error('Refusing to overwrite an unrecognized build directory');
  fs.mkdirSync(buildRoot, { recursive: true }); fs.writeFileSync(marker, 'Generated by tools/build-pages.cjs\n');
  if (!output.startsWith(buildRoot + path.sep) || path.basename(output) !== 'pages') throw new Error('Invalid build path');
  fs.rmSync(output, { recursive: true, force: true });
  fs.cpSync(path.join(root, 'dist'), output, { recursive: true });
  const action = endpoint
    ? '<p>เข้าสู่ระบบเพื่ออัปโหลด วิเคราะห์ และแบ่งไฟล์เสียงในพื้นที่ของคุณ</p><a class="button button-primary" href="' + endpoint + '/demo/">เข้าสู่ Web Demo</a>'
    : '<p role="status">Web Demo อยู่ระหว่างเตรียมระบบ ยังไม่เปิดรับไฟล์เสียงในขณะนี้</p><p>ติดตามการเปิดใช้งานหรือสอบถามผ่านช่องทางติดต่อของ Audio Tech Labs</p><a class="button button-outline" href="/#contact">ติดต่อ Audio Tech Labs</a>';
  const template = fs.readFileSync(path.join(__dirname, 'templates', 'demo-entry.html'), 'utf8');
  fs.writeFileSync(path.join(output, 'demo', 'index.html'), template.replace('<!-- DEMO_ACTION -->', action));
  fs.writeFileSync(path.join(output, '.nojekyll'), '');
  console.log('Pages build: ' + output + (endpoint ? ' (verified demo endpoint)' : ' (demo maintenance page)'));
  return output;
}
if (require.main === module) buildPages().catch(error => { console.error(error.message); process.exitCode = 1; });
module.exports = { buildPages };
