'use strict';
const fs = require('node:fs'), path = require('node:path');

async function buildPages({ root = path.resolve(__dirname, '..') } = {}) {
  const buildRoot = path.resolve(root, '.site-build');
  const output = path.join(buildRoot, 'pages');
  const marker = path.join(buildRoot, '.pages-generated-by-atl');
  fs.mkdirSync(buildRoot, { recursive: true });
  if (!output.startsWith(buildRoot + path.sep) || path.basename(output) !== 'pages') throw new Error('Invalid build path');
  if (fs.existsSync(output) && !fs.existsSync(marker)) throw new Error('Refusing to overwrite an unrecognized Pages build directory');
  fs.writeFileSync(marker, 'Generated by tools/build-pages.cjs\n');
  fs.rmSync(output, { recursive: true, force: true });
  fs.cpSync(path.join(root, 'dist'), output, { recursive: true });
  fs.writeFileSync(path.join(output, '.nojekyll'), '');
  console.log('Cloudflare Pages build: ' + output);
  return output;
}

if (require.main === module) buildPages().catch(error => { console.error(error.message); process.exitCode = 1; });
module.exports = { buildPages };
